# Generated by Django 5.0.1 on 2024-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0326', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '一级靓号'), (2, '二级靓号'), (3, '三级靓号'), (4, '四级靓号')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '未售卖'), (2, '已售卖')], default=2, verbose_name='状态')),
            ],
        ),
    ]
